import assert from 'node:assert'
import test from 'node:test'
import $ from '../../helpers'
import { run } from './'

test('Day 08 — Sample', () => {
  const sample = $.sample(
    `
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    `
  )

  assert.strictEqual(run(sample), 14)
  assert.strictEqual(run(sample, true), 34)
})

test('Day 08 — Solutions', () => {
  const input = $.readInput(import.meta)
  assert.strictEqual(run(input), 392)
  assert.strictEqual(run(input, true), 1235)
})
